// SoftwareApplication JSON-LD for the pricing / product page. Encodes the
// four tiers with AggregateOffer so an AI engine extracting price information
// has the full range plus a representative lowest-tier offer.

import { site } from '@/lib/site';
import { organizationSchema } from './organization';

export const softwareApplicationSchema = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  '@id': `${site.url}/#software`,
  name: 'ChurnStop',
  alternateName: 'ChurnStop for WooCommerce Subscriptions',
  applicationCategory: 'BusinessApplication',
  applicationSubCategory: 'Cancellation save flow',
  operatingSystem: 'WordPress 6.0+, WooCommerce 8.0+, WooCommerce Subscriptions 4.0+',
  softwareVersion: '0.1.0',
  url: `${site.url}/pricing`,
  description:
    'Cancellation save flow for WooCommerce Subscriptions. Intercepts cancel clicks with conditional offers (discount, pause, skip renewal, tier-down, extend trial, product swap) and reports MRR preserved. FTC click-to-cancel compliant by default.',
  // Generated by app/pricing/opengraph-image.tsx at build time; Next.js emits
  // a stable URL at /pricing/opengraph-image (plus a file-hash variant).
  image: `${site.url}/pricing/opengraph-image`,
  author: { '@id': organizationSchema['@id'] },
  publisher: { '@id': organizationSchema['@id'] },
  featureList: [
    'Conditional branching save flows',
    'Six offer types: discount, pause, skip renewal, tier-down, extend trial, product swap',
    'A/B testing of flows and offers',
    'Save-rate and MRR-preserved dashboard',
    'FTC click-to-cancel compliance enforcement',
    'Cohort LTV analytics (Growth tier)',
    'Winback email automation (Growth tier)',
    'White-label admin and multi-site management (Agency tier)',
    'GDPR data hooks',
    'Native WooCommerce Subscriptions integration',
  ],
  offers: {
    '@type': 'AggregateOffer',
    priceCurrency: 'USD',
    lowPrice: '0',
    highPrice: '399',
    offerCount: 4,
    offers: [
      {
        '@type': 'Offer',
        name: 'Free',
        description:
          'Single-path save flow, discount and pause offers, save count dashboard, click-to-cancel compliance, GDPR data hooks. Installed from wordpress.org.',
        price: '0',
        priceCurrency: 'USD',
        category: 'Free',
        url: 'https://wordpress.org/plugins/churnstop/',
      },
      {
        '@type': 'Offer',
        name: 'Starter',
        description:
          'Everything in Free plus conditional branching flows, six offer types, A/B testing, save-rate dashboard, email support. Preserves up to $10k MRR per month.',
        price: '79',
        priceCurrency: 'USD',
        priceSpecification: {
          '@type': 'UnitPriceSpecification',
          price: '79',
          priceCurrency: 'USD',
          unitText: 'MONTH',
        },
        category: 'subscription',
        url: `${site.url}/pricing`,
      },
      {
        '@type': 'Offer',
        name: 'Growth',
        description:
          'Everything in Starter plus cohort LTV analytics, winback automation, customer segmentation, priority support. Preserves up to $50k MRR per month.',
        price: '199',
        priceCurrency: 'USD',
        priceSpecification: {
          '@type': 'UnitPriceSpecification',
          price: '199',
          priceCurrency: 'USD',
          unitText: 'MONTH',
        },
        category: 'subscription',
        url: `${site.url}/pricing`,
      },
      {
        '@type': 'Offer',
        name: 'Agency',
        description:
          'Everything in Growth plus white-label admin, multi-site central management, cross-store benchmarks, SLA support. Unlimited MRR preserved.',
        price: '399',
        priceCurrency: 'USD',
        priceSpecification: {
          '@type': 'UnitPriceSpecification',
          price: '399',
          priceCurrency: 'USD',
          unitText: 'MONTH',
        },
        category: 'subscription',
        url: `${site.url}/pricing`,
      },
    ],
  },
};
